### PR TITLE
use Selenide instead of pure Selenium

### PR DESCRIPTION
**Pull request by asolntsev**
P.S. I think I could also simplify class Order and method IndexView.getListedOrders()

Unfortunately, I failed to run the tests, so I could not verify if the tests are still green after my changes.
But I hope at least the idea should be clear.

### CODE REVIEW

**Comment by sdaschner** [comment]
Thanks a lot for the PR!

I like the syntactical simplifications and extra features (e.g. checking for element _enabled_). I've made small changes, to keep the test case free from Seleni{um,ide}

Oh, what exactly failed for you to execute the tests? I only had to update my Chrome Version, but that was it

**Comment by asolntsev** [comment]
I said in README, I executed
```
docker network create --subnet=192.168.42.0/24 dkrnet
./local-build.sh
./local-run-env.sh
```

but after these commands, a webapp was not running on `http://localhost:8001` (nor `http://localhost:8080` nor `http://localhost:8081` nor `http://localhost:8002` not `http://localhost:8082`).

**Comment by sdaschner** [comment]
🤔 Huh, interesting. I just checked again and it worked (it should have three Docker containers, two listening to `localhost:8001` and `:8002`).

Maybe something fails for the containers and you can grab a `docker logs`? In case they already crashed, in which removing `--rm` in the script should keep them around after they stopped. Would help me to know, since I assumed that approach was quite straightforward and would work for folks.

**Comment by asolntsev** [comment]
@sdaschner I removed `--rm` and executed `docker logs` after container death - and found the problem! :)

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:359)
	... 6 more
Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/sebastian_daschner/coffee_shop/orders/entity/Order$HibernateProxy$vmfaFUaC, offset=6
```

Apparently the problem is that your build/docker scripts use Java14, but I compiled the project with Java15 because my "sdkman" only suggest OpenJDK 8, 11 or 15. :)

**Comment by sdaschner** [comment]
Hm... That's interesting, since the `pom.xml` explicitly specifies 14, so even if you build using 15, shouldn't that support to compile/build it in a compatible way...?

**Comment by asolntsev** [comment]
Hm... yes, it should... Strange..

By the way, is it ok that in `barista` subproject, pom.xml declares `<maven.compiler.target>13</maven.compiler.target>`?

**Pull request merged**
